[package]
name = "print_bot"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.6.0-rc.1"
libusb = "0.3"
log = "0.4"
env_logger = "0.6.1"
escposify = "0.1.4"
image = "*"
dither = "1.3.6"
